name: parkinson_de_bolso
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  diacritic: ^0.1.1
  intl: ^0.16.1
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  image_picker: ^0.6.3
  path: ^1.6.4
  path_provider: ^1.5.1
  provider: ^4.0.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/images/