name: parkinson_de_bolso
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  diacritic: ^0.1.1
  http: ^0.12.0+2
  intl: ^0.16.1
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  image_picker: ^0.6.3
  camera: ^0.7.0+1
  path: ^1.6.4
  path_provider: ^1.5.1
  provider: ^4.0.1
  fl_chart: ^0.12.2
  shared_preferences: ^0.5.12+4
  circular_countdown_timer: ^0.0.9
  flutter_animation_progress_bar: ^1.0.6
  amazon_cognito_identity_dart_2: ^0.1.25+1
  flutter_aws_s3_client: ^0.5.2
  flutter_dotenv: ^3.1.0
  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: ^0.0.1
  month_picker_dialog: ^0.3.3
  carousel_slider: ^1.4.1
  flutter_local_notifications: 1.4.4+1
  rxdart: ^0.24.0
  awesome_dialog: ^1.3.2
  url_launcher: 3.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/test/test1.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_launcher_name:
  name: "Parkinson de Bolso"
  