name: parkinson_de_bolso
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  diacritic: ^0.1.1
  http: ^0.12.0+2
  intl: ^0.16.1
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  image_picker: ^0.6.3
  camera: ^0.7.0+1
  path: ^1.6.4
  path_provider: ^1.5.1
  provider: ^4.0.1
  fl_chart: ^0.12.2
  shared_preferences: ^0.5.12+4
  circular_countdown_timer: ^0.0.9
  flutter_animation_progress_bar: ^1.0.6
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/images/